
### GET - pobierz wszystkie dane
GET http://localhost:3000/api/photos HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbnlPdGhlckRhdGEiOiIxMjMiLCJpYXQiOjE3MTc2MTMyMjAsImV4cCI6MTcxNzYxNDEyMH0.WoUpBgyqBB0TfLUn7tIhd-uxZv36tL4xa66YTAEeeUU
### GET - pobierz konkretne zdjecie
GET http://localhost:3000/api/photos/1717094884612 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbnlPdGhlckRhdGEiOiIxMjMiLCJpYXQiOjE3MTc2MTMyMjAsImV4cCI6MTcxNzYxNDEyMH0.WoUpBgyqBB0TfLUn7tIhd-uxZv36tL4xa66YTAEeeUU
###
DELETE http://localhost:3000/api/photos/1111111111 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbnlPdGhlckRhdGEiOiIxMjMiLCJpYXQiOjE3MTc2MTMyMjAsImV4cCI6MTcxNzYxNDEyMH0.WoUpBgyqBB0TfLUn7tIhd-uxZv36tL4xa66YTAEeeUU
######
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

user_album1234
------FormBoundary1234